import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Layout from "@/components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio v0.1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Navbar />
        <h1>Main</h1>
        <Link href="/projects">Projects</Link>
      </Layout>
    </>
  );
}
